### ISSUE TITLE
optionString is not used to try to initialize mediaDevices.getUserMedia()

### ISSUE THREAD

**Issue by ToastyMallows** [AckerApple/ack-angular-webcam#1]
On line 175 of webcam.component.js, the fallback is supposed to try to initialize the webcam using the configuration string `optionString` instead of a JavaScript object, but the `optionObject` variable is used both times.

The error message "Both configs failed. Neither object nor string works" leads me to believe that the optionString is supposed to be used during the second attempt. Unless I'm reading this incorrectly.

```javascript
// if the config object failes, we try a config string
_this.browser.mediaDevices.getUserMedia(optionObject)  // <--- this should be optionString
```

**Comment by AckerApple** [comment]
I have received your issue report. I will review and update by/on Monday if I find the same to be true as claimed in bug report (fallback had been tested working recently). Have you tried making your prescribed change in your local copy of node_modules/ack-angular-webcam? Did everything then begin to work as expected. If you make the change and all works, please consider issueing a pull request to save me time. 

For extra knowledge: You may know, this package is a fork from a library that had way too many issues. I recommend you continue using my fork but wanted to ensure you had the knowledge. Forked from : https://www.npmjs.com/package/ng2-webcam

**Comment by ToastyMallows** [comment]
Hey no rush on this at all, I was just looking through the code because I got curious as to how it was written and noticed this.  I was just working on a little test application using this repo.  I saw it and I was wondering why the variable wasn't being used so I figured I would write it up.

Everything worked as expected, I actually don't know of a browser that would default to using an option string instead of an object.

I had issues with ng2-webcam, seen here: https://github.com/PeterKassenaar/ng2-webcam/issues/1

**Comment by AckerApple** [comment]
I have addressed your reported issue in v1.2.11

Also for your knowledge, the source files are NOT the default branch.

Source branch: https://github.com/ackerapple/ack-angular-webcam/tree/master

(default) distribution branch: https://github.com/ackerapple/ack-angular-webcam

**Comment by AckerApple** [comment]
Please review and close as I prefer reporter to close issues

**Comment by ToastyMallows** [comment]
Just looked at the code, looks like `optionString` is being used now, looks good! Again, I have no way to test this as I'm not sure what browser defaults to using a string instead of an object for `getUserMedia()`.

**Comment by AckerApple** [comment]
Thank you friend. I checked the original code that I forked from and it too had this typo that you have pointed out. I feel/think the same thing you do about that part of the code almost appearing to be pointless.

Later good guy
