### ISSUE TITLE
Failed to execute 'getUserMedia' on 'MediaDevices': parameter 1 ('constraints') is not an object.

### ISSUE THREAD

**Issue by erickvalderrama** [AckerApple/ack-angular-webcam#10]
Hello, i need help with this (please)

Failed to execute 'getUserMedia' on 'MediaDevices': parameter 1 ('constraints') is not an object.

**Comment by AckerApple** [comment]
Don't be shy on details... I would need a lot more. What browser?

This demo page is working for what this package is designed for: https://ackerapple.github.io/ack-angular-webcam/

**Comment by erickvalderrama** [comment]
i used google Chrome, angular 2 and without https, just http on localhost works. But i don't know because on http don't work it

**Comment by AckerApple** [comment]
Well Angular2 is now on version 4.4.0-RC.0 but I do not think that is your problem.

My Google Chome: Version 60.0.3112.113 (Official Build) (64-bit)

Did maybe you deny access to the camera on accident?

Does the demo page work in your Google chrome?
https://ackerapple.github.io/ack-angular-webcam/

I've had too many comments of "thanks" and "job well done" for this project. I don't think it's anything on with this project. This project is used in production in several applications.

Good luck

**Comment by AckerApple** [comment]
ALSO, please try new version 1.3.12

I think the error you are getting is misleading so I tried to improve the error logging.

**Comment by AckerApple** [comment]
Ohhhhhhhhh hey!

Yo it's a web browser security rule. You have to be on https or localhost. That's your isssue. Google it

Closing this issue

**Comment by AckerApple** [comment]
https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https

**Comment by erickvalderrama** [comment]
thanks!
