### ISSUE TITLE
camera not working when app is hosted at different system

### ISSUE THREAD

**Issue by psharneja** [AckerApple/ack-angular-webcam#18]
Hi, 

I've my Angular app running at one system and access that app from other system and getting below error on that:

> DOMException: Only secure origins are allowed 

> TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': parameter 1 ('constraints') is not an object.

> Error:  Both configs failed. Neither object nor string works

**Comment by AckerApple** [comment]
Yeah it’s well documented. Webcams only work on localhost and https
