### ISSUE TITLE
Observer disconnect truble

### ISSUE THREAD

**Issue by nikes** [AckerApple/ack-angular-webcam#19]
if using this lib problem in -> this.observer.disconnect()

```
ERROR TypeError: Cannot read property 'disconnect' of undefined
at WebCamComponent.ngOnDestroy (webcam.component.js:233)
at callProviderLifecycles (core.es5.js:11182)
at callElementProvidersLifecycles (core.es5.js:11147)
at callLifecycleHooksChildrenFirst (core.es5.js:11131)
at destroyView (core.es5.js:12470)
at callViewAction (core.es5.js:12619)
at execEmbeddedViewsAction (core.es5.js:12557)
at destroyView (core.es5.js:12468)
at callViewAction (core.es5.js:12619)
at execComponentViewsAction (core.es5.js:12531)
```

**Comment by AckerApple** [comment]
What browser are you getting this error in?

The code that is erring for you, is using Html5 MutationObserver, which is supported by most all browsers as seen here: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

The destroy button on this page, which calls the disconnect method, works in Chrome, Firefox, and Safari as seen here: https://ackerapple.github.io/ack-angular-webcam/

The code you have reported, has proven itself to be working, you will need to give me more new details.

Link to self, the code in question is located here:
https://github.com/AckerApple/ack-angular-webcam/blob/master/lib/webcam.component.ts#L280

**Comment by nikes** [comment]
I using this code on Chrome 61.0.3163.100 & 62.0.3202.75
I fix it add to code `if (this.observer)` but it's crutches...
Version Ack-angular-webcam 1.4.0

```
Your global Angular CLI version (1.4.9) is greater than your local
version (1.0.4). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.4
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/compiler-cli: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/platform-server: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.0.4
```

**Comment by AckerApple** [comment]
Hmmmmmmmmmmmm. This library is in use by several people who’ve reported and fixed other issues. This issue you are reporting is not seen by anyone else.

Can you give me a link to your code or a plunker example? I’m under the assumption you are doing something different than the rest of us. How can you get me something I can work with?

**Comment by AckerApple** [comment]
Also this is not an Angular issue. This package uses Html5 MutationObserver, which has a disconnect method. Your browser environment must not be what it is to the rest of us. I wonder too if you are performing any odd DOM manipulation that would break things this library expects.

I don’t dunno, sorry

**Comment by nikes** [comment]
Trouble in render this component in angular project, sry for this isset.

**Comment by AckerApple** [comment]
Hey, slow down and take your time. I say this because you have so many typos in all your communications and I see that as evidence that your approach must be fast and hard without learning what incompasses the things that you are building. I bet you are burning a lot of time trying to get things working the way you want and not how they are expected to work. And maybe upgrade from a super cool icon, to an everyday trustworthy photo of yourself.

Just a bunch of judgements and suggestions. I think we are now even for burning each others time. Farewell programming friend
