### ISSUE TITLE
Both configs failed. Neither object nor string works. 

### ISSUE THREAD

**Issue by hemnath11** [AckerApple/ack-angular-webcam#21]
I got this error after uploaded my file into server. Please help me how to fixes this

**Comment by AckerApple** [comment]
I’ve never received an issue report with less details. Based on the lack of details, I feel safe to assume you are doing something wrong.

Without details, I cant help you. Many people are using this package in production.

**Comment by AckerApple** [comment]
Feel free to open issue back up. But I will need far more details
