### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by Belouccio** [AckerApple/ack-angular-webcam#24]
Hi! I'm trying to build my project using webpack and get this error

`ERROR in Error: Metadata version mismatch for module /home/developer/projects/demo/front/node_modules/ack-angular-webcam/index.d.ts, found version 4, expected 3`

Can you help me please?

**Comment by AckerApple** [comment]
I am under the assumption that this issue is because this package is now built with Angular5 and is known to not work with Angular4

If stuck in Angular4, let me know and I’ll dig you up the install command for the last known version for Angular4

**Comment by Belouccio** [comment]
I have update Angular to the version 5 and get this error

`ERROR in Error: Type WebCamComponent in /home/developer/projects/demo/front/node_modules/ack-angular-webcam/webcam.component.d.ts is part of the declarations of 2 modules: AppModule in /home/developer/projects/demo/front/src/app/app.module.ts and WebCamModule in /home/developer/projects/demo/front/node_modules/ack-angular-webcam/webcam.module.d.ts! Please consider moving WebCamComponent in /home/developer/projects/demo/front/node_modules/ack-angular-webcam/webcam.component.d.ts to a higher module that imports AppModule in /home/developer/projects/demo/front/src/app/app.module.ts and WebCamModule in /home/developer/projects/demo/front/node_modules/ack-angular-webcam/webcam.module.d.ts. You can also create a new NgModule that exports and includes WebCamComponent in /home/developer/projects/demo/front/node_modules/ack-angular-webcam/webcam.component.d.ts then import that NgModule in AppModule in /home/developer/projects/demo/front/src/app/app.module.ts and WebCamModule in /home/developer/projects/demo/front/node_modules/ack-angular-webcam/webcam.module.d.ts.`

**Comment by Belouccio** [comment]
Sorry man:) I have import WebCamComponent instead of WebCamModule. Now it work fine!
Thank you! Have a good day!
P.S.Sorry for my bad English :)

**Comment by AckerApple** [comment]
Awesome!

Aok on the bad english, especially because you have a face on your profile icon. I appreciate the human touch in this digital age.

Follow, like or do whatever you do to keep in touch. Cya
