### ISSUE TITLE
Reopened #26

### ISSUE THREAD

**Issue by kk4fun** [AckerApple/ack-angular-webcam#27]
@AckerApple Hi. About issue #26
According to github rules I cannot re-open your own issues if a repo collaborator closed them :)
So, please reopen it by yourself and delete current issue.
I've updated to 1.7.3 version , but unfortunately result is almost the same.
Almost - error object now is undefined.

**Comment by AckerApple** [comment]
The example page is working perfectly. You’re going to need to prove it’s not working. I bet you are still on the old version.

Photo of it working on example page is attached

![43d413b7-d118-4bb6-b5f2-af9055c63167](https://user-images.githubusercontent.com/7964429/35194443-9fcd7a0e-fe81-11e7-8e12-2931c0bc8943.png)

**Comment by kk4fun** [comment]
Can u share this example page source code (ts + html) template?
Is this approach to handle error right?

**public onCameraError(error: Error): void {
       console.log(error);
    }**
Camera declaration in html

<ack-webcam class="take-photo-page-container-webcam"
                            [(ref)]="webcam"
                            [options]="webcamOptions"
                            (success)="onCameraSuccess($event)"
                            **(catch)="onCameraError($event)**">
  </ack-webcam>

My web cam options object

this.webcamOptions = {
            audio: false,
            fallbackSrc: 'fallback/jscam_canvas_only.swf',
            height: 400,
            video: false,
            width: 400,
        };

**Comment by AckerApple** [comment]
The demo page link is in the main documentation at the top : https://ackerapple.github.io/ack-angular-webcam/

Why in your options do you have video false and audio false? That doesn’t seem right at all

**Comment by kk4fun** [comment]
https://github.com/AckerApple/ack-angular-webcam/blob/master/example/app/app.component.ts
Here i see only one catch. But does it cover allow/ block permission case? I just dont understand , sorry.
```
captureBase64(webcam:WebCamComponent){
    return webcam.getBase64()
    .then(base=>{
      this.captured = new Date()
      this.base64 = base
      setTimeout(()=>webcam.resizeVideo(), 0)
    })
    .catch( e=>console.error(e) )
  }
```
but on this page u use another approach , like me 

https://github.com/AckerApple/ack-angular-webcam/blob/master/README.md

**onCamError(err){}**

<ack-webcam
  [(ref)]   = "webcam"
  [options] = "options"
  (success) = "onCamSuccess($event)"
  **(catch)   = "onCamError($event)"**
></ack-webcam>

And i need this case. but it dont work =\

**Comment by kk4fun** [comment]
> Why in your options do you have video false and audio false? That doesn’t seem right at all
I just don't need audio and video :) i need just photo and proper error message from **(catch) = "onCamError($event)"** function

**Comment by AckerApple** [comment]
I think you deleted your comment but heads up, a photo is taken using the video stream. You can’t just take a picture only. Options are video and audio, there is no “photo” option
