### ISSUE TITLE
Metadata version mismatch for module... found version 4, expected 3

### ISSUE THREAD

**Issue by OnlyAGhost** [AckerApple/ack-angular-webcam#28]
Hi! I just installed ack-angular-webcam for some testing, when I import the module in an angular-cli project I am getting a Metadata version mismatch for module <path to module>, found version 4, expected 3.

**Comment by AckerApple** [comment]
I have had this issue reported time and time again so I know the exact issue.

You are on Angular4 and you need to be on Angular5

**Comment by OnlyAGhost** [comment]
Lol, I just saw it and was closing it. Thank you for your fast response!

If anyone is looking for more depth take a peek at #25 

Thanks for your work on this!!

**Comment by AckerApple** [comment]
You are welcome and thank you for having a legit face as your github icon (a rare find)
