### ISSUE TITLE
Reflect camera view

### ISSUE THREAD

**Issue by EduhCosta** [AckerApple/ack-angular-webcam#29]
Can i do reflect camera view??

**Comment by AckerApple** [comment]
What's that? Never heard of. Google didn't have any results relative to getUserMedia() functionality.

Do you mean change between selfie camera and environment camera? Then yes.

Everything this package can do, is demo'd here: https://ackerapple.github.io/ack-angular-webcam/

**Comment by EduhCosta** [comment]
When I open the camera view, the screen is mirrored ie:
If you lift your left hand it is on the side of the screen.

The Desired Behavior:
Raise your left hand and it will stand on the left side of the screen.

How can I do this??

**Comment by AckerApple** [comment]
Excellent question...... Hmmmmmmm, we need to start googling how to flip the stream OR flip the video elements output.

This task starts we researching. Let me know if you have any resources that would help us figure out how to do what you are asking.

This package completely revolves around getUserMedia() and the video element for output.

**Comment by AckerApple** [comment]
It seems we will need the information on this page: https://christianheilmann.com/2013/07/19/flipping-the-image-when-accessing-the-laptop-camera-with-getusermedia/

**Comment by EduhCosta** [comment]
Woow, It`s true, Thanks

**Comment by AckerApple** [comment]
I still need to add the ability to reflect the camera. Reopening this issue until I add that ability into this package. I can see needing this setting you’ve brought up

**Comment by AckerApple** [comment]
Alright. Thank you much for bringing this to my attention. Reflect is now a built-in binding of this package.

Npm updated

Demo page update now has reflect button

1.7.5 now has [reflect]
