### ISSUE TITLE
Hardcoded values in template for swf url

### ISSUE THREAD

**Issue by meghalp** [AckerApple/ack-angular-webcam#3]
var template = "\n<video id=\"video\" *ngIf=\"isSupportWebRTC && videoSrc\" [src]=\"videoSrc\" autoplay>Video stream not available</video>\n\n<object *ngIf=\"isFallback\" data=\"jscam_canvas_only.swf\">\n  Video stream not available\n  <param name=\"FlashVars\" value=\"mode=callback&amp;quality=200\">\n  <param name=\"allowScriptAccess\" value=\"always\">\n  <param name=\"movie\" value=\"jscam_canvas_only.swf\">\n</object>\n";
Here "jscam_canvas_only.swf" is passed as hardcoded which should take actually fallbacksrc.
This will create issue in passing the fallbacksrc in options.

Can you please remove the hardcode dependencies?
Requesting you to please revert me once you have any update over it.

-Meghal

**Comment by AckerApple** [comment]
I think you are right. Will get back at you today

**Comment by AckerApple** [comment]
I have fixed.

It is still hardcoded but dynamically updated. If I used angular {{options.fallbackSrc}} then I would also need to employ safeUrl sanitization.

After success, please close issue

**Comment by AckerApple** [comment]
I would prefer you to close this issue. It is reported fixed by other parties. Give you a few days to respond.

**Comment by meghalp** [comment]
Hi,
Actually i have investigated the issue with the ie 11 and have something to
share which i will share you today.
Hope this will help many users.

Regards,
Meghal

--

Experience all the benefits of your EHR from anywhere, with our mobile app,
IMSGo. Accessibility, Anytime without Constraints. Contact your account
manager now!

*Elbert Meghal Patel* | Meditab Software Inc.

Sr. Programmer Analyst

E-mail: meghalp@meditab.com

Phone: +91 812-832-1739

www.meditab.com

[image: -Meditab Logo (Colored)-01.png]

[image: facebook.png] <https://www.facebook.com/EHRSoftware/>[image:
linkedin.png] <https://www.linhttps//www.linkedin.com/company-beta/322993/>[image:
twitter.png] <https://twitter.com/meditabian>

**Comment by meghalp** [comment]
Hi, All.

I found 2 things that need to be done to run in IE11.

@AckerApple:  As per my investigation, first you need to add "
type=\"application/x-shockwave-flash\"" in <object *ngIf=\"isFallback\" > to
run specifically in IE11.

Moreover as previously I suggested to change in template to adhere dynamic
fallbacksrc and you implemented that in setupFallback  method.

But IE doesn't download swf file on change in data attribute in object
element. It need to create full object element so to have a workaround,
instead of creating full object,
i just cloned and replace again and which works very well in IE11 and all
browser.

Also in cloning while initializing flashplayer make sure to pass the clone
element.


WebCamComponent.prototype.setupFallback = function () {
this.isFallback = true;
var vidElm = this.getVideoElm();
vidElm.setAttribute('data', this.options.fallbackSrc);
var params = vidElm.getElementsByTagName('param');
for (var x = params.length - 1; x >= 0; --x) {
if (params[x].getAttribute('name') == 'movie') {
params[x].setAttribute('value', this.options.fallbackSrc);
break;
}
}
var clone = vidElm.cloneNode(true);
this.flashPlayer = new videoHelp.Fallback(clone);
vidElm.parentNode.replaceChild(clone, vidElm);
};

Last 3 lines.

Hope this may help to run this component in all browsers.
even i tested in safari.

This is really a great webcam component by you and it's really simple to
use and does almost everything related to webcam interface.

Kindly commit the same so that i can take the latest and then will close
the issue.

Regards,


--

Experience all the benefits of your EHR from anywhere, with our mobile app,
IMSGo. Accessibility, Anytime without Constraints. Contact your account
manager now!

*Elbert Meghal Patel* | Meditab Software Inc.

Sr. Programmer Analyst

E-mail: meghalp@meditab.com

Phone: +91 812-832-1739

www.meditab.com

[image: -Meditab Logo (Colored)-01.png]

[image: facebook.png] <https://www.facebook.com/EHRSoftware/>[image:
linkedin.png] <https://www.linhttps//www.linkedin.com/company-beta/322993/>[image:
twitter.png] <https://twitter.com/meditabian>

**Comment by meghalp** [comment]
Hi, All.

I found 2 things that need to be done to run in IE11.

@AckerApple:  As per my investigation, first you need to add " type=\"application/x-shockwave-flash\"" in <object *ngIf=\"isFallback\" > to run specifically in IE11.

Moreover as previously I suggested to change in template to adhere dynamic fallbacksrc and you implemented that in setupFallback 
 method.

But IE doesn't download swf file on change in data attribute in object element. It need to create full object element so to have a workaround, instead of creating full object,
i just cloned and replace again and which works very well in IE11 and all browser.

Also in cloning while initializing flashplayer make sure to pass the clone element.


WebCamComponent.prototype.setupFallback = function () {
        this.isFallback = true;
        var vidElm = this.getVideoElm();
        vidElm.setAttribute('data', this.options.fallbackSrc);
        var params = vidElm.getElementsByTagName('param');
        for (var x = params.length - 1; x >= 0; --x) {
            if (params[x].getAttribute('name') == 'movie') {
                params[x].setAttribute('value', this.options.fallbackSrc);
                break;
            }
        }
      
        **var clone = vidElm.cloneNode(true);
        this.flashPlayer = new videoHelp.Fallback(clone);
        vidElm.parentNode.replaceChild(clone, vidElm);**
      
    };

Last 3 lines.

Hope this may help to run this component in all browsers.
even i tested in safari.

This is really a great webcam component by you and it's really simple to use and does almost everything related to webcam interface.

Kindly commit the same so that i can take the latest and then will close the issue.


Regards,
Meghal

**Comment by meghalp** [comment]
Also one more thing that there should be something that destroy the object if user close the browser or move to another page

**Comment by AckerApple** [comment]
Jolly good show @meghalp 

I'll get it done today. A different way but I'll get it done. You'll be my I.E. tester. Safari has always been working on fallback (just mentioning)

Also, we have an ngOnDestroy that does cleanup and Angular destroys the class as well so I foresee no additional cleanup needed even for your proposed changes. From my experience, I'm almost certain you are playing traditional JavaScript worry based memory cleanup. Your destroy suggestion would only be a faster release of memory.

**Comment by AckerApple** [comment]
Please install 1.3.6 and try now

**Comment by meghalp** [comment]
I installed and is working fine.
But i have one observation:
Camera is not getting turned off unless you close the browser in IE11
In Chrome its working fine but need to close the tab.
If i go on any other page inside the application the webcam is not getting off.
For chrome & Mozilla  i found the solution to stop without refresh:

 In  WebCamComponent.prototype.ngOnDestroy() method
instead of  if (this.stream) {
            this.stream.getTracks()[0].stop();
        }

Need to loop as below as there are 2 tracks running.
 this.stream.getTracks().forEach(function (track) {
                 track.stop();
  });

Kindly look into this issue.
I think this would be the last one. :)

**Comment by AckerApple** [comment]
Please confirm you are experiencing the same issue on this page, by using the destroy button: https://ackerapple.github.io/ack-angular-webcam/

The destroy and create function turn on/off the camera in Safari and Chrome successfully.

Regardless, you have provided sound solid code to remove tracks with a loop. I will implement that right away.

Great find!

**Comment by AckerApple** [comment]
I released 1.3.7 . The example page has been updated too. So everything may work as expected. If so please close issue.

**Comment by meghalp** [comment]
Done.
Thanks for the quick response.

--

Experience all the benefits of your EHR from anywhere, with our mobile app,
IMSGo. Accessibility, Anytime without Constraints. Contact your account
manager now!

*Elbert Meghal Patel* | Meditab Software Inc.

Sr. Programmer Analyst

E-mail: meghalp@meditab.com

Phone: +91 812-832-1739

www.meditab.com

[image: -Meditab Logo (Colored)-01.png]

[image: facebook.png] <https://www.facebook.com/EHRSoftware/>[image:
linkedin.png] <https://www.linhttps//www.linkedin.com/company-beta/322993/>[image:
twitter.png] <https://twitter.com/meditabian>
