### ISSUE TITLE
how do I turn off the webcam?

### ISSUE THREAD

**Issue by stalinrangel** [AckerApple/ack-angular-webcam#31]
hi, how do I turn off the webcam?

**Comment by AckerApple** [comment]
On the demo page, the ack-angular-webcam is wrapped in a *ngIf condition. When you press the destroy button (in demo page), the *ngIf condition becomes false and the webcam is destroyed and stopped

**Comment by stalinrangel** [comment]
Gracias por tu aporte!!!

**Comment by AckerApple** [comment]
Please help the reputation of this package by starring, following, and any other social actions you can think of so others may find their way to this package.

El Cielo es azul. Just don't go telling everyone
