### ISSUE TITLE
cameraType DEPRECATED?

### ISSUE THREAD

**Issue by lolaswift** [AckerApple/ack-angular-webcam#35]
Wonderful component. thank you very much Acker!
What does this mean:
cameraType : 'front' || 'back'//DEPRECATED
I am rewriting my cordova app with PWA and I need to take photo from both front and back camera of mobile devices. Can I use this component for that?

**Comment by AckerApple** [comment]
um, i think that was going to be deprecated but that has since changed.

Looking into that right now for confirmation

**Comment by lolaswift** [comment]
Quickest reply I've ever got. You're awesome Acker!
If I can get the camera work, I am pretty much able to get away from cordova and switch to PWA and that would be great.

**Comment by AckerApple** [comment]
Please continue to use cameraType. I thought it was going to be deprecated but iOs certainly needs it as of this post. I had just not removed the comments.

Next push those comments will drop off.

Thank you much for the appreciation. I have been on the other end.

Please star, follow, and perform any other social actions that will naturally progress the popularity of this package.

You take care and close this issue, please

Here, have a song: https://www.youtube.com/watch?v=vXmqauitBkM&index=28&list=PLM110C9j-n5PDE6g_BRoT_qU05otrBOGR

**Comment by lolaswift** [comment]
Many thanks again Acker! 
Will do.
and thx for the song.
