### ISSUE TITLE
Camera options not configured correctly

### ISSUE THREAD

**Issue by superduck35** [AckerApple/ack-angular-webcam#37]
Hi @AckerApple 

I am using your camera and am trying to use only the back camera so have set up my options like so:

	`cameraOptions: any = {audio: false, video: true, cameraType: 'back'};`

After the user gets asked for permissions, and the video stream shows, it seems to default to the front camera. Once they navigate away and come back, the back camera gets used.

Unable to remedy this situation, I then tried to add a camera flip button to change the options from 'front' to 'back' on the fly, but the camera video stream doesn't seem to respond to me changing this setting.. 

Can you please help

**Comment by AckerApple** [comment]
Do not use cameraOptions.cameraType

Look up in my README the one way binding called [facingMode]

**Comment by AckerApple** [comment]
I have produced and published updated version 1.9.0 which removes all references of options.cameraType

**Comment by superduck35** [comment]
Thanks for your reply @AckerApple. We are using angular 4 and so have installed version 1.5 of your package. It is not possible for us to update to 5.x.

Is this possible to do on 1.5? as I don't think facingMode has been implemented at this point.

**Comment by AckerApple** [comment]
facingMode wasn't discovered NOT working until we went to Angular5

Sorry I have no immediate help for you. That took awhile to get right, flippin' iOs.

Thoughts? What else can I do for ya?

**Comment by AckerApple** [comment]
Second thought,

1. fork my code
2. change all angular packages from 5 to 4
3. run `npm run build`
4. Put the /dist folder where ever your project needs it to be

Point being, I think everything should work just fine because I think functionality wise for this package Ng4 and Ng5 are no difference. The only reason they are not compatible is because of the bundle step writes different output code.

Follow? That's a lot to do but I'd do in your shoes if stuck in Ng4

**Comment by alsco77** [comment]
Thanks for the instructions. Just away from the computer at the moment,
will give this a go when I get back to my desk.

**Comment by alsco77** [comment]
Hey man, seem to be missing some scripts. There are no dependencies so nothing runs on npm install and can't seem to run any other npm commands here..

**Comment by AckerApple** [comment]
I think you deleted some of your last comments about not finding the package dependencies. That would be because you are in the wrong branch.

**Comment by superduck35** [comment]
Yep I realised that! Haha. Got it up and running following your instructions, however instead of just copying the dist folder (which would get overridden when a new clone/npm install is run) I followed this guide to update my npm package source. 

https://coderwall.com/p/q_gh-w/fork-and-patch-npm-moduels-hosted-on-github

Thanks!

**Comment by AckerApple** [comment]
Great job! Close this issue if satisfied.

Also please star, follow, and perform any other social actions that might naturally boost the popularity of this package
