### ISSUE TITLE
Camera dimension will not set properly on Mobile

### ISSUE THREAD

**Issue by hoomb** [AckerApple/ack-angular-webcam#38]
Hello @AckerApple,

I have another issue regarding to setting the Camera dimension on Mobile devices while Desktop works properly. I have tested this on both iPhone (Safari) and Android Devices and both don't show the camera in compelete width (Please refer to attached Image)

Here is the code I'm using:

```
  options = {
    audio: false,
    video: true,
    width: 280,
    height: 210
  };

      <ack-webcam
        [(ref)]="webcam"
        [options]="options"
        (success)="onCamSuccess()"
        (catch)="onCamError($event)"
        [facingMode]="facingMode"
      ></ack-webcam>
```

even setting the "video" dimension in CSS could not solve the problem:

```
      video {
        width: 280px;
        height: 210px;
        display: inline-block;
      }
```

Regarding to https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia there are more Options to set the Video constraints like "min", "max", "exact" or "ideal"

Could that be the Problem?

![clipboard](https://user-images.githubusercontent.com/2638655/36424399-75f67a4e-1643-11e8-93af-32ef2d1193a6.jpg)

**Comment by AckerApple** [comment]
Most often you do not need to set a width height as the component auto adjust size to the max available. Sometimes when it doesn’t, the one way binding useParentWidthHeight is needed.

If you are hard coding the width height, it should just work. Play with it a little longer.

One of us needs to create a plunker like online environment. It would help us a lot. I’m loaded today but you get me a plunker like environment then we can weed issues out much faster

**Comment by AckerApple** [comment]
It's possible this pull request #39 might be related to your issue

**Comment by hoomb** [comment]
Here is a Plunkr which I've created for this issue. 
https://plnkr.co/edit/P5XTwM3cCMsY1uawJ4Zs?p=preview

Running version: https://run.plnkr.co/cWNFr7PTsHwgN0cs/

If you browse it with your mobile, you will see the same picture as above.

Regarding to mentioned pull request, I would make it more flexible as described in https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia by defining all "min", "max", "exact" and "ideal" settings.

**Comment by AckerApple** [comment]
reviewing...

Pretty loaded today though

**Comment by AckerApple** [comment]
The plunker demo does not seem to work what so ever. No error. Just picture of camera. Tried tapping on everything. Camera never loaded.

Link two gives message of: Oh dear, something didn't go quite right. Internal Server Error

Please revise and advise me when to try again

**Comment by hoomb** [comment]
I have checked the Plunkr with 2 PCs and my Mobile and everything worked. Would you please try the Plunkr Projekt itself und check the console to see if there are any errors?

**Comment by AckerApple** [comment]
I have updated to 1.9.1 . It now allows for video width/height controls. This package always has, it's just now been documented and included in the demo page.

Goto demo page, use "sizing" and alter the video width height min max ideal exact.

Let me know if this help you in the right direction

**Comment by AckerApple** [comment]
options.video.width and options.video.height

**Comment by AckerApple** [comment]
I cannot get your plunker to work because of the following error, of which I am unsure how to resolve:

VideoCapture permission has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

**Comment by hoomb** [comment]
Thank you for fix. But I still can't get the Camera in proper size on Mobiles. I have no idea why my browsers resize the video section.

**Comment by AckerApple** [comment]
I think this is an aspect ratio "issue"

In that you think you should just get the video to be whatever width height you want but the video element maintains aspect ratio WITHOUT skewing or cropping the image.

The wrapping video element goes to the right width height but *video* has to maintain size to be able to fit within the video element.

I think, to do what you are asking more settings would be needed if they are available at all.

Too combat your issue, I have in the past used a cropping method of putting a fixed width/height div with overflow:hidden
