### ISSUE TITLE
Missing TypeScript File ?

### ISSUE THREAD

**Issue by z639** [AckerApple/ack-angular-webcam#4]
Hi,
A general question,  shouldn't there be a "webcam.component.ts" file, given that there is a "webcam.component.d.ts" declaration file it would seem that typescript is being used ?

"webcam.component.js" even looks like code that the typescript compiler would generate.

**Comment by AckerApple** [comment]
You're asking me for general knowledge. I would appreciative you closing this issue. I will continue to provide some help though.

The ts files are on a different branch then the npm released files : https://github.com/AckerApple/ack-angular-webcam/tree/master/lib

The ts files are not included in the distribution branch for many "common" knowledge reasons that we all come across when learning how to make distributable typescript packages
