### ISSUE TITLE
How to change the image size

### ISSUE THREAD

**Issue by guilhermewm** [AckerApple/ack-angular-webcam#42]
I need an example of how to change the size of the webcam image, because the actual image comes 640x480 all the time, and i need a 1280x720 base64 picture. 
I´m using Angular 4 and i try a lot of methods, but doesn´t work.

**Comment by AckerApple** [comment]
It's like you're asking me how to resize an image. Use any tool out there, right?

This library connects to a camera and then renders the image naturally as original. Soooooooooooo if its not the size you want, go resize it.

You're asking for direct help, too directly. I'm not that kinda guy. I'm busy

**Comment by AckerApple** [comment]
thank you
