### ISSUE TITLE
facingMode (rear camera) not working on Android Chrome

### ISSUE THREAD

**Issue by ajaysaini235** [AckerApple/ack-angular-webcam#47]
Hi,

We are using ack-webcam in our application. It is working brilliantly on laptop while using front-camera. However, we want to use it on mobile (Google Chrome). We are using a property [facingMode]="environment" for using mobile's rear camera. It is working fine on Mozilla Firefox (firefox asks for front-cam OR back-cam) but on Android Google Chrome still the front camera is opening. 

Please provide a solution. Its very urgent.

Thanks !

**Comment by AckerApple** [comment]
Search my issues. This one comes up a lot and I need to document it.

facingMode is IOS only. Android and all others, pass deviceId around
