### ISSUE TITLE
Demo source available?

### ISSUE THREAD

**Issue by anakinjay** [AckerApple/ack-angular-webcam#49]
Hi All, is the demo source available anywhere?   I'm trying to figure out how to use ack-media-devices directive properly, and would really love to see how it was used in the demo.

**Comment by anakinjay** [comment]
Crap nevermind, just realized I was looking at the dist branch.  For anyone else wonderin in the future,  the master branch has example.

**Comment by AckerApple** [comment]
https://github.com/AckerApple/ack-angular-webcam/tree/master/example/app

.... and may the force be with you

**Comment by AckerApple** [comment]
![image](https://user-images.githubusercontent.com/7964429/39088442-19f5cbde-4580-11e8-9725-cb69abce62f6.png)
