### ISSUE TITLE
Error closing the webcam

### ISSUE THREAD

**Issue by BrianMuhimbura** [AckerApple/ack-angular-webcam#5]
Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at proto.(anonymous function).
when am trying to exit the webcam

**Comment by asarapas** [comment]
Was getting the same error. Fixed it and submitted Pull request. In the meantime I have overwrote 'ngOnDestroy' like this in my component:
` onCamSuccess = (stream: MediaStream) =>
    {
        this.webcam.ngOnDestroy = () => {
            this.webcam.observer.disconnect();
            window.removeEventListener('resize',this.webcam.onResize);
            var vid = this.webcam.getVideoElm();
            if (vid && vid.pause) {
                vid.pause();
            }
            if (this.webcam.stream) {
                this.webcam.stream.getTracks()[0].stop();
            }
        }
    };`

**Comment by BrianMuhimbura** [comment]
Hello. thanx for the feedback. was wondering though where than ngOnDestroy method you are overwriting. can i get a snippet on how u handled that. thanx

**Comment by AckerApple** [comment]
Pull request accepted. NPM publish later today and will comment again. Good show friends. Pull request mean the most!

**Comment by BrianMuhimbura** [comment]
Thanx that was helpful thanx a bunch

**Comment by AckerApple** [comment]
Published to npm

**Comment by asarapas** [comment]
Tested and works perfect now. Thank you for the great library.
