### ISSUE TITLE
i can't open the back camera in i phone

### ISSUE THREAD

**Issue by neutron92** [AckerApple/ack-angular-webcam#51]
i can't open the back camera in i phone

it return  onSuccess

**Comment by AckerApple** [comment]
Works just fine on demo page, just tested: https://ackerapple.github.io/ack-angular-webcam/

iOS uses facingMode settings and all other devices use camera id specification to change cameras

**Comment by AckerApple** [comment]
Closing this issue if no further comments

**Comment by rajgsdei** [comment]
Hello @AckerApple, could you please share the source code of the link you shared above? I'm getting error while switching camera using device Ids, so I want to see how you have switched front and back camera.

**Comment by AckerApple** [comment]
I use both facingMode and deviceId cause Apple for who knows why, only uses facingMode

[See code here, that drives the demo](https://github.com/AckerApple/ack-angular-webcam/blob/master/example/app/app.pug#L147)
