### ISSUE TITLE
XHR error

### ISSUE THREAD

**Issue by Syarit** [AckerApple/ack-angular-webcam#54]
Hello, 

I am sorry if this problem is not related to your code but when I try to import your library I get a "(SystemJS) XHR Error (404 Not Found) loading https://localhost:8080/ack-angular-webcam"

It's probably a parameter in a file somewhere but I couldn't find anything similar to my problem online.

The npm install worked fine and my IDE finds it (VSCode). 

Here is the file that triggers the error: 
```

import`` { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import { rest } from '../../service/rest.service.js';
import { ParamWeb } from '../../Components/paramWeb/paramWeb.component.js';
import { RecherchePiece } from './app.component.js';
import { ArboView } from '../../Components/ArboView/arbo-view.js';
import { ArboFilter } from '../../Utils/arbo_filter/ArboFilter.js';
import { ArboEquips_application } from '../arbo_equips_app/app.component.js';
import { ArboFilterSet } from '../../Components/ArboFilterSet/arbo_filter_set.js';
import { Directory_application } from '../directory_app/app.component.js';
import { ModalFormService } from '../../Components/ModalForm/modal_form_service.js';
import { PiecesViewer } from '../../Components/PiecesViewer/pieces-viewer.js';
import { OrderBy } from '../../Utils/order_by/OrderBy.js';
import { PiecesManager } from '../../Components/PiecesManager/pieces-manager.js';
import { QRCodeReader } from '../../Components/QRCodeReader/QRCodeReader.js';
import { TranslatePipe } from '../../Components/translate.pipe.js';
import { WebCamModule } from 'ack-angular-webcam/index.js';

@NgModule({
    imports: [BrowserModule, FormsModule,HttpModule, WebCamModule],
    providers : [rest,ModalFormService,{provide: Boolean, useValue: false}],
    declarations: [RecherchePiece, ArboView, ArboFilter, ArboEquips_application,ArboFilterSet, Directory_application, ParamWeb, PiecesViewer
    ,OrderBy,PiecesManager,TranslatePipe, QRCodeReader],
    bootstrap: [RecherchePiece]
})
export class AppModule { } 

```

Stacktrace:
![image](https://user-images.githubusercontent.com/46035831/68684111-3b6da300-0568-11ea-831c-c5253e61689d.png)

EDIT: 
I forgot to say that if I add 

`'ack-angular-webcam': 'npm:ack-angular-webcam',`

to the systemjs.config.js file I get a " XHR error (403 Forbidden) " (the rest of the stacktrace staying essentially the same)

Thank you

**Comment by AckerApple** [comment]
You’ve given me enough context to make the assumption that you are going about working with Angular and this code wrong.

I don’t have time to troubleshoot your package management issues (SystemJs).

**Comment by Syarit** [comment]
Alright fair enough, thank you anyway and sorry for the loss of time.
