### ISSUE TITLE
Webcam component does not work correctly when used in Modal Dialog

### ISSUE THREAD

**Issue by asarapas** [AckerApple/ack-angular-webcam#7]
I am using WebCam component in the bootstrap modal. It works perfect when first time opened, but captures same image after second open. And image it what is on camera just before closing dialog for the first time. Seems like something is not disposed correctly, but can't trace what.

Here I have created small app which can be used to reproduce problem:
[WebCamTest.zip](https://github.com/AckerApple/ack-angular-webcam/files/1180387/WebCamTest.zip)
Open Dialog, capture images. Works fine.
Close Dialog.
Open again. Same image is getting captured.

After refreshing page cycle can be repeated.

**Comment by AckerApple** [comment]
Please stand by for two minutes. Instructions on way

**Comment by AckerApple** [comment]
Please follow the process below:

1. Please uninstall any npm installation of ack-angular-webcam

2. Use github installation
```
npm install github:ackerapple/ack-angular-webcam
```

3. Ensure version is 1.3.8

4. Test your ack-angular-webcam works as it did before

5. Test your issue is fixed


Let me know any issues you encounter. You are my testing eyes on this so I await on you to npm publish.

**Comment by asarapas** [comment]
1.3.7 seems to be latest on the NPM:
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: ack-angular-webcam@1.3.8
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.2, 1.3.1, 1.3.0, 1.2.13, 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.7, 1.2.6, 1.2.5, 1.2.4

**Comment by AckerApple** [comment]
Please read my instructions more carefully. The whole point was NOT to use the npm version. Please install from GitHub using the command I offered. Try again

**Comment by asarapas** [comment]
doh. Sorry. On it.

**Comment by asarapas** [comment]
Couldn't get Git working through the corporate proxy, but updated files manually and problem seems to be solved in 1.3.8. Unreal timing! :-) Thank you very much!

**Comment by AckerApple** [comment]
Thank you kindly new friend. I will publish to npm shortly

**Comment by AckerApple** [comment]
I have published 1.3.8 to npm

I added the following to the next release of ack-angular-webcam, thought maybe you might be interested:

## If You Like ack-webpack
You might also want to give these packages a try
- [ack-angular](https://www.npmjs.com/package/ack-angular)
- [ack-angular-fx](https://www.npmjs.com/package/ack-angular-fx)
- [ack-css-boot](https://www.npmjs.com/package/ack-css-boot)
