### ISSUE TITLE
issue in internet explorer 11

### ISSUE THREAD

**Issue by keymaker19** [AckerApple/ack-angular-webcam#8]
Hello I can't make the component to work in internet explorer 11. Can you help me out? I added the reference in the index page to the polyfill getUserMedia.js. I can't even see the demo working on IE 11. Maybe I need to do things differently.
Thank you

**Comment by AckerApple** [comment]
Internet Explorer is known to be working by other users of this library, search the issues and seek help from those users. You are giving me next to no details to help you with, plus I have not a care in my body to help troubleshoot Internet Explorer issues.

This demo page, the last I heard, is known to be working for Internet Explorer 11 : https://ackerapple.github.io/ack-angular-webcam/

I'll give you some time to close this issue on your own or to report further findings

**Comment by keymaker19** [comment]
This is the error that I'm having in internet explorer 11.

![image](https://user-images.githubusercontent.com/10747284/29683386-31b59ce2-88dc-11e7-9e53-6cf68f5ea093.png)

**Comment by keymaker19** [comment]
By the way, I was able to reproduce the issue in different workstations.

**Comment by AckerApple** [comment]
Yeah sorry, you wont find help from me for Internet Explorer

I knew to be cautious and say that other people said its working. I bet they used some sort of polyfill or something.

Good luck

**Comment by AckerApple** [comment]
I think I know what it is. Stand by 3 hours

**Comment by AckerApple** [comment]
This is our issue, I'm bundling to ES5 code but you will need ES3, as seen here : https://github.com/AckerApple/ack-angular-webcam/blob/master/lib/tsconfig.json#L3

I will rebuild the files when at laptop. You can test

**Comment by keymaker19** [comment]
Ok, thank you so much


Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by AckerApple** [comment]
Try now. I updated github, npm, and demo page.

Ensure you have version 1.3.10

Try the demo page again

**Comment by keymaker19** [comment]
the demo page doesn't work.

**Comment by AckerApple** [comment]
Hmmmmmmm, same error? New error?

**Comment by keymaker19** [comment]
Same error


Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by AckerApple** [comment]
I can't believe I gave this issue the time of day let alone just wasted an hour on it.

I'm done man. Your on your own. I borrowed a fellow employees IE11 and it requires too many hoops to jump through.

I'm not mad atch ya. I do think you need to stand beside me in rejecting supporting IE.

Good luck. I have reverted all the ES3 notation and the project will go back to before this reported issue.

ALSOOOOOOO, I can't stand having an open issue for IE so I will be closing this issue. It's like saying this project doesn't work on a calculator, of course it doesn't work on garbage tech.

**Comment by keymaker19** [comment]
I have been looking for an alternative but couldn't find none for angular
4. I agree about internet explorer, but it is a customer requirement, not
my requirement. I guess you will have this issue with several developers.
it's up to you guys if you are going to address the problem in internet
explorer or not. You can reject it, but it is still there. Customers
request it and every mayor web framework/libraries support it.

2017-08-25 11:44 GMT-04:00 Acker Dawn Apple <notifications@github.com>:

**Comment by AckerApple** [comment]
I hear you. I bet I come off sassy mouthed but my point of view is simply => I don't have issue reports from developers, that my packages doesn't work on an abacus... Get it? Internet Explorer is the abacus of tomorrow/today ACCEPT and abacus I bet will be long used forever longer than Internet Explorer will be used.

Educate your customer, that's my feeling. Your job should be to illustrate the costs wasted to accommodate the browser. How much time have you wasted? How much more time do you have to spend once you even get past this Internet Explorer only issue?

I do not envy you. Your strive to accommodate Internet Explorer is seen a costly waste of time with little to be gained. Most likely cost less to buy a new computer for everyone who is still on Internet Explorer.

Farewell

**Comment by AckerApple** [comment]
Updated readme for you

https://www.npmjs.com/package/ack-angular-webcam#internet-explorer
