### ISSUE TITLE
Doesn't support internet explorer 11

### ISSUE THREAD

**Issue by kvramirez89** [AckerApple/ack-angular-webcam#9]
Hello the directive throws the error 'Object doesn't support property or method 'subscribe' in Internet Explorer 11. Even the demo website does it. Our team have tested it using several workstations. I have read this:

"A polyfill will be needed. The function Object.assign and other missing functionality in Internet Explorer will need to be polyfilled."

 We did it, but still it doesn't work.

**Comment by AckerApple** [comment]
Issue #8 should be a fun read for you

I have updated the package for you, see here: https://www.npmjs.com/package/ack-angular-webcam#internet-explorer
